GET http://localhost:3000/hello

###
POST http://localhost:3000/api/groups
Content-Type: application/json

{
    "name": "string",
    "password": "string",
    "imageUrl": "http://example.com/your-image-url.jpg",
    "isPublic": true,
    "introduction": "string"
}

###
PUT http://localhost:3000/api/groups/{groupId}
Content-Type: application/json

{
    "name": "string",
    "password": "string",
    "isPublic": true,
    "introduction": "Updated introduction",
    "imageUrl": "http://example.com/updated-image-url.jpg"
}

### 그룹 등록 (POST /api/groups)
POST https://codeit-demo-be.onrender.com/api/groups
Content-Type: application/json

{
    "name": "Study Group",
    "password": "securepassword",
    "imageUrl": "http://example.com/image.jpg",
    "isPublic": true,
    "introduction": "A group for studying together."
}

### 그룹 목록 조회
GET https://codeit-demo-be.onrender.com/api/groups
Content-Type: application/json

###

### 그룹 수정 (PUT /api/groups/:groupId)
PUT http://localhost:3000/api/groups/66cc499f8c59a2b310141f2f
Content-Type: application/json

{
    "name": "Updated Study Group",
    "password": "securepassword",
    "imageUrl": "http://example.com/new-image.jpg",
    "isPublic": false,
    "introduction": "Updated introduction for the study group."
}

###

### 그룹 삭제 (DELETE /api/groups/:groupId)
DELETE http://localhost:3000/api/groups/66cc49378c59a2b310141f2c
Content-Type: application/json

{
    "password": "securepassword"
}


### 그룹 상세 정보 조회 (GET /api/groups/:groupId)
GET http://localhost:3000/api/groups/66cc48c2a2253bf6c312a03a


### 그룹 조회 권한 확인 (비밀번호 확인) (POST /api/groups/:groupId/verify-password)
POST http://localhost:3000/api/groups/66cc48c2a2253bf6c312a03a/verify-password
Content-Type: application/json

{
    "password": "securepassword"
}

###

### 그룹 공감하기 (POST /api/groups/:groupId/like)
POST http://localhost:3000/api/groups/66cc48c2a2253bf6c312a03a/like

###

### 그룹 공개 여부 확인 (GET /api/groups/:groupId/public-status)
GET http://localhost:3000/api/groups/66cc48c2a2253bf6c312a03a/is-public

###

### 이미지 업로드 (POST /api/image) 터미널에서 입력
curl -X POST http://localhost:3000/api/image -F "image=@data/img/hello.png"

